// Generated by CoffeeScript 1.12.6
(function() {
  var roleType, roles;

  roles = ["admin", "user"];

  roleType = {
    type: "role",
    role: "admin",
    adminLogin: function() {
      return true;
    },
    opearation: {
      create: true,
      read: true,
      update: true,
      "delete": true
    }
  };

}).call(this);
