// Generated by CoffeeScript 1.12.6
(function() {
  var alertName, name, person;

  name = "Naveen Gupta";

  person = true;

  alertName = function(n) {
    return alert(n);
  };

  if (person === true && name !== "xyz") {
    alertName(name);
  }

  if (person(!false || name === "Naveen Gupta")) {
    alertName(name);
  }

}).call(this);
