// Generated by CoffeeScript 1.12.6
(function() {
  var colours;

  colours = "Blue";

  switch (colours) {
    case "Blue":
      alert("blue");
      break;
    case "Green":
    case "Yellow":
      alert("Green/Yellow");
      break;
    default:
      alert("no colours");
  }

}).call(this);
