// Generated by CoffeeScript 1.12.6
(function() {
  var fruits, i, item, j, k, len, len1, len2;

  fruits = ["mango", "banana", "apple", "orange"];

  for (i = 0, len = fruits.length; i < len; i++) {
    item = fruits[i];
    alert(item);
  }

  for (j = 0, len1 = fruits.length; j < len1; j++) {
    item = fruits[j];
    alert(item);
  }

  for (k = 0, len2 = fruits.length; k < len2; k++) {
    item = fruits[k];
    if (item !== "mango") {
      alert(item);
    }
  }

  fruits = (function() {
    var l, len3, results;
    results = [];
    for (l = 0, len3 = fruits.length; l < len3; l++) {
      item = fruits[l];
      results.push(item + "s");
    }
    return results;
  })();

}).call(this);
