// Generated by CoffeeScript 1.12.6
(function() {
  var htmlStr, name, str;

  name = "naveen";

  str = "lorem epsom lurur msddedi";

  htmlStr = "<h1>\n    hello\n</h1>";


  /*
   this
   is 
   block 
   comment
   */

  alert("My name is: " + name + " and my age is: " + (20 + 5));

}).call(this);
