// Generated by CoffeeScript 1.12.6
(function() {
  var alertName, name, person;

  name = "Naveen Gupta";

  alertName = function(n) {
    return alert(n);
  };

  if (name != null) {
    alertName("name exists");
  }

  if (typeof person !== "undefined" && person !== null) {
    alertName("person not defined");
  }

  person = "";

  if (person == null) {
    person = "person";
  }

  if (person != null) {
    alertName("person is defined now");
  }

}).call(this);
