// Generated by CoffeeScript 1.12.6
(function() {
  var fruits, iLike,
    slice = [].slice;

  fruits = ["mango", "banana", "apple", "orange"];

  iLike = function() {
    var most, rest, second;
    most = arguments[0], second = arguments[1], rest = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    alert("i like " + most);
    alert("i also like " + second);
    return alert("i also enjoy " + rest);
  };

  iLike.apply(null, fruits);

}).call(this);
