// Generated by CoffeeScript 1.12.6
(function() {
  var copyFruits, first, firstExcludeLast, fruits, ref, rest;

  fruits = ["mango", "banana", "apple", "orange", "pineapple", "grapes"];

  first = fruits.slice(0, 3);

  firstExcludeLast = fruits.slice(0, 2);

  rest = fruits.slice(2);

  copyFruits = fruits.slice(0);

  [].splice.apply(fruits, [2, 3].concat(ref = ["peach", "pear", "guava"])), ref;

}).call(this);
